version: '3.4'

services:
  API:
    image: complianceapi
    build:
      context: .
      dockerfile: API/src/Dockerfile
    volumes:
    - ./API:/app
    ports:
      - "5000:5000"

  UI:
    image: complianceui
    build:
      context: .
      dockerfile: Compliance.UI/Dockerfile
    volumes:
      - ./Compliance.UI:/app
    ports:
      - "4200:4200"
